In [2]:
import numpy as np

In [1]:
print("Lista Prática Cálc. Numérico.")

Lista Prática Cálc. Numérico.


In [2]:
def _LU_(Matriz):
    tamanho = Matriz.shape[0] # Pega o tamanho da matriz.
    U = Matriz.copy() # Copia a matriz original para a uper.
    L = np.eye(tamanho, dtype=np.double) # Cria uma matriz do tamanho da original para L.
    # Indo até o tamanho da matriz.
    for i in range(tamanho):
        pivo = U[i+1:,i]/U[i,i] # Calcula o Pivo
        L[i+1:,i] = pivo # A lower é composta de pivos.
        U[i+1:] -= pivo[:, np.newaxis] * U[i] # Substrai o pivo a todas as linhas da matriz com o pivo.
    return L, U # Retorna o resultado das duas matrizes.

# Método de Cholesky visto em aula.
# De k=0 até tamanho_matriz,faz:
# lkk = sqrt(m[k][k])
# de i=k até tamanho_matriz, faz:
# lik = (aik - somatorio[m=1 até k-1](lim*lmk))/lkk
def cholesky(Matriz):
    Matriz2 = np.copy(Matriz)
    tamanho = Matriz2.shape[0]
    L = np.zeros_like(Matriz2)
    for j in range(tamanho):
        L[j, j] = np.sqrt(Matriz2[j, j])
        for i in range(j + 1, tamanho):
            L[i, j] = Matriz2[i, j] / L[j, j]
        for k in range(j + 1, tamanho): # Começa o segundo loop.
            for m in range(k, tamanho): # Loop da somatória.
                Matriz2[m, k] = Matriz2[m, k] - L[k, j] * L[m, j]
    return L # A L @ L.T tem que ser a própria matriz Original.

In [3]:
print("\n=======================================================================\n")
print("Exercício 1)")

ex1_matriz_a = np.array([[2, -1, 1],
[3, 3, 9],
[3, 3, 5]], dtype='float')

ex1_matriz_b = np.array([[1.012, -2.132, 3.104],
[-2.132, 4.906, -7.013],
[3.104, -7.013, 0.014]])

ex1_matriz_c = np.array([[2, 0, 0, 0],
[1, 1.5, 0, 0],
[0, -3, 0.5, 0],
[2, -2, 1, 1]])

ex1_matriz_d = np.array([[2.1756, 4.0231, -2.1732, 5.1967],
[-4.0231, 6.0000, 0.0000, 1.1973],
[-1.0000, -5.2107, 1.1111, 0.0000],
[6.0235, 7.0000, 0.0000, -4.1561]])

L_a, U_a = _LU_(ex1_matriz_a)
L_b,U_b = _LU_(ex1_matriz_b)
L_c,U_c = _LU_(ex1_matriz_c)
L_d,U_d = _LU_(ex1_matriz_d)

print("a)\n")
print("Matriz:\n", ex1_matriz_a)
print("\nL:\n",L_a)
print("\nU:\n",U_a)
print("\nVerificando com numpy se Matriz=L@U: ",np.allclose(ex1_matriz_a, L_a@U_a))
print("\n=======================================================================\n")

print("b)\n")
print("Matriz:\n", ex1_matriz_b)
print("\nL:\n",L_b)
print("\nU:\n",U_b)
print("\nVerificando com numpy se Matriz=L@U: ",np.allclose(ex1_matriz_b, L_b@U_b))
print("\n=======================================================================\n")

print("c)\n")
print("Matriz:\n", ex1_matriz_c)
print("\nL:\n",L_c)
print("\nU:\n",U_c)
print("\nVerificando com numpy se Matriz=L@U: ",np.allclose(ex1_matriz_c, L_c@U_c))
print("\n=======================================================================\n")

print("d)\n")
print("Matriz:\n", ex1_matriz_d)
print("\nL:\n",L_d)
print("\nU:\n",U_d)
print("\nVerificando com numpy se Matriz=L@U: ",np.allclose(ex1_matriz_d, L_d@U_d))
print("\n=======================================================================\n")



Exercício 1)


NameError: name 'np' is not defined

In [43]:
print("\n=======================================================================\n")
print("Exercício 2)")
"""
Método utilizado na aula.
A = np.random.rand(5,5)
A = A @ A.T
b = A @ np.ones(5)

Modo de resolução visto para os sistemas:

Sistema original
(L @ L.T) @ x = b

Sistema modificado
L @ Y = b
L.T @ x = Y
"""

#=========================================================================
#2) a)
ex2_matriz_a = np.array([[2,-1,0], [-1,2,-1], [0,-1,2]], dtype='float')
aux_ex2_matriz_a = ex2_matriz_a

ex2_matriz_a = ex2_matriz_a @ ex2_matriz_a.T
b1 = ex2_matriz_a @ np.ones(ex2_matriz_a.shape[0])
L_a = cholesky(ex2_matriz_a)
L1 = np.linalg.cholesky(ex2_matriz_a)
#=========================================================================

#2) b)
ex2_matriz_b = np.array([[4, 1, 1, 1], [1, 3, -1, 1], [1, -1, 2, 0], [1, 1, 0, 2]], dtype='float')
aux_ex2_matriz_b = ex2_matriz_b

ex2_matriz_b = ex2_matriz_b @ ex2_matriz_b.T
b2 = ex2_matriz_b @ np.ones(ex2_matriz_b.shape[0])
L_b = cholesky(ex2_matriz_b)
L2 = np.linalg.cholesky(ex2_matriz_b)
#=========================================================================

#2) c)
ex2_matriz_c = np.array([[4, 1, -1, 0], [1, 3, -1, 0], [-1, -1, 5, 2], [0, 0, 2, 4]], dtype='float')
aux_ex2_matriz_c = ex2_matriz_c

ex2_matriz_c = ex2_matriz_c @ ex2_matriz_c.T
b3 = ex2_matriz_c @ np.ones(ex2_matriz_c.shape[0])
L_c = cholesky(ex2_matriz_c)
L3 = np.linalg.cholesky(ex2_matriz_c)
#=========================================================================

#2) d)
ex2_matriz_d = np.array([[6, 2, 1, -1], [2, 4, 1, 0], [1, 1, 4, -1], [-1, 0, -1, 3]], dtype='float')
aux_ex2_matriz_d = ex2_matriz_d

ex2_matriz_d = ex2_matriz_d @ ex2_matriz_d.T
b4 = ex2_matriz_d @ np.ones(ex2_matriz_d.shape[0])
L_d = cholesky(ex2_matriz_d)
L4 = np.linalg.cholesky(ex2_matriz_d)
#=========================================================================

print("a)\n")
print("Matriz:\n", aux_ex2_matriz_a)
print("\nL:\n",L_a)
print("\nComparando com o método do resultado do numpy:\n",L1)
print("\nVerificando com numpy se Matriz=L@L.T: ",np.allclose(ex2_matriz_a, L1@L1.T))
print("\n=======================================================================\n")

print("b)\n")
print("Matriz:\n", aux_ex2_matriz_b)
print("\nL:\n",L_b)
print("\nComparando com o método do resultado do numpy:\n",L2)
print("\nVerificando com numpy se Matriz=L@L.T: ",np.allclose(ex2_matriz_b, L2@L2.T))
print("\n=======================================================================\n")

print("c)\n")
print("Matriz:\n", aux_ex2_matriz_c)
print("\nL:\n",L_c)
print("\nComparando com o método do resultado do numpy:\n",L3)
print("\nVerificando com numpy se Matriz=L@L.T: ",np.allclose(ex2_matriz_c, L3@L3.T))
print("\n=======================================================================\n")

print("d)\n")
print("Matriz:\n", aux_ex2_matriz_d)
print("\nL:\n",L_d)
print("\nComparando com o método do resultado do numpy:\n",L4)
print("\nVerificando com numpy se Matriz=L@L.T: ",np.allclose(ex2_matriz_d, L4@L4.T))
print("\n=======================================================================\n")



Exercício 2)
a)

Matriz:
 [[ 2. -1.  0.]
 [-1.  2. -1.]
 [ 0. -1.  2.]]

L:
 [[ 2.23606798  0.          0.        ]
 [-1.78885438  1.67332005  0.        ]
 [ 0.4472136  -1.91236577  1.06904497]]

Comparando com o método do resultado do numpy:
 [[ 2.23606798  0.          0.        ]
 [-1.78885438  1.67332005  0.        ]
 [ 0.4472136  -1.91236577  1.06904497]]

Verificando com numpy se Matriz=L@L.T:  True


b)

Matriz:
 [[ 4.  1.  1.  1.]
 [ 1.  3. -1.  1.]
 [ 1. -1.  2.  0.]
 [ 1.  1.  0.  2.]]

L:
 [[ 4.35889894  0.          0.          0.        ]
 [ 1.60591014  3.06937333  0.          0.        ]
 [ 1.14707867 -1.90335441  1.03026818  0.        ]
 [ 1.60591014  1.11457691  0.2711232   1.4509525 ]]

Comparando com o método do resultado do numpy:
 [[ 4.35889894  0.          0.          0.        ]
 [ 1.60591014  3.06937333  0.          0.        ]
 [ 1.14707867 -1.90335441  1.03026818  0.        ]
 [ 1.60591014  1.11457691  0.2711232   1.4509525 ]]

Verificando com numpy se Matriz=L